### ISSUE TITLE
请教cookie相关问题

### ISSUE THREAD

**Issue by deng47** [comwrg/youtubu2bilibili#1]
我在自己两年前的cookie里面并没有找到_cnt_dyn=0和_cnt_dyn__ckMd5这两个字段，其他字段都有。请问是我找的地方不对吗？谢谢

**Comment by comwrg** [comment]
网页上会抓包吗？
直接抓cookie复制粘贴上去就可以了
主要是bilibili登录要手动验证，暂时没法弄

**Comment by comwrg** [comment]
没有没关系的，有些cookie是没啥用的，你粘贴上去看可以上传就可以了

**Comment by deng47** [comment]
谢谢这么快的回复！

我把cookie换成自己的，然后修改了一下你的bilibili.py（改成从命令行输入视频title、source、tag等参数）再上传，期间没有报错，但投稿都卡在b站审核那里了。

昨天我试过传四、五次日语的广播节目，结果审核总是提示“该稿件在上传过程中出现了错误，请尝试重新上传视频文件
”。于是我尝试传一个只有虫鸣鸟叫的环境白噪音视频，没多久就通过审核，播放一切正常。
今天我又再尝试，结果连白噪音视频都不能通过审核。

现在我还没有搞清楚是我真的在修改脚本的时候出问题导致上传出错，还是b站审查视频的锅。



​

2017-06-24 17:20 GMT-07:00 comwrg <notifications@github.com>:

**Comment by comwrg** [comment]
等会又空我再试试吧，之前上传了几个视频都审核成功了，也就一个礼拜之前

**Comment by deng47** [comment]
谢谢，主要是现在网络舆论环境恶化，加上b站准备搞实名认证，让我分不清是代码问题还是审查问题。

2017-06-24 17:59 GMT-07:00 comwrg <notifications@github.com>:

**Comment by comwrg** [comment]
审核不通过提示什么信息？

2017年6月25日星期日，siqi deng <notifications@github.com> 写道：

**Comment by deng47** [comment]
退回理由
稿件中发现1个问题。
分P诊断

   -  P1
   该稿件在上传过程中出现了错误，请尝试重新上传视频文件


2017-06-24 18:27 GMT-07:00 comwrg <notifications@github.com>:

**Comment by comwrg** [comment]
那应该是上传的问题，你看看封面有没有生成

2017年6月25日 09:29，"siqi deng" <notifications@github.com>写道：

**Comment by deng47** [comment]
我不清楚你看不看得到我的附件图片，我这些视频最后都是自己生成了封面的

2017-06-24 20:03 GMT-07:00 comwrg <notifications@github.com>:

**Comment by comwrg** [comment]
有生成封面的话说明视频是上传成功的

2017-06-25 11:07 GMT+08:00 siqi deng <notifications@github.com>:

**Comment by deng47** [comment]
所以很可能是b站审核的锅？谢谢你的解答，麻烦你了

2017-06-24 20:13 GMT-07:00 comwrg <notifications@github.com>:

**Comment by deng47** [comment]
我觉得我可能发现问题原因了。我上传的几个片源是用rtmpdump下载的flv。我试着换成其他的mp4以后就好像没有出错了。
虽然同样的flv文件上传youtube完全没有问题

**Comment by comwrg** [comment]
嗯，懂了，源码里有个问题

在 2017年6月26日 上午2:59，siqi deng <notifications@github.com>写道：

**Comment by comwrg** [comment]
试下bug#1分支的源码

**Comment by deng47** [comment]
用新分支的bilibili.py上传后r.text出现报错：
{"OK":-1,"info":"No file in body."} 6 6
{"OK":0,"info":"Chunks error, should be 0"}

**Comment by comwrg** [comment]
再上传试试？

**Comment by deng47** [comment]
试过flv和mp4文件都一样问题

**Comment by comwrg** [comment]
试试最新master的，我这里测试都是可以的

**Comment by deng47** [comment]
我觉得是我用rtmpdump下载的视频编码有问题，我直接正常网页端投稿都是显示上传出错的
现在我用ffmpeg转成mp4以后就没有问题了
谢谢
